# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "logformat"
version = "0.0.1"
name = "Appication Log Formatter Pack"

[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"

[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
